"""Where examples come from: a public set, a synthetic scene, an operator's verdicts.

Each builder turns one kind of source into a :class:`~offrow.learn.examples.Manifest`
with the label basis stated on every row. None of them pools with another; the
training loader reads every manifest under ``data/examples/`` and the scorecard
breaks results down by source, so a model that only learned synthetic corn
cannot hide behind a synthetic-heavy average.

**USU-Corn-WeedDB** labels three weed species and nothing else. Its annotated
tiles are exhaustively annotated (every weed in the tile has a box), so ground
that is far from every box is, by the dataset's own contract, not a weed. Those
chips are labelled by the repo's vegetation mask: mostly vegetation means the
corn, mostly not means soil. The basis says so, because a derived label is not
an annotated one.

**Synthetic scenes** carry exact truth: every crop plant, every weed and every
patch of bare soil is known. They are the only source that populates the
smallest diameter bin, which is the one the flight spec is about, and the only
one where shadows, wheel tracks and wet soil can be switched on to be learned
as "other".

**Operator verdicts** are the archive the scout already keeps
(``weed_observations`` and the ``weed-chips`` bucket). They are the only labels
from the imagery operators actually fly, and the only ones that come with the
scout's own chip framing. Few today; the point of the loop is that there will
be more.
"""

from __future__ import annotations

import json
import math
from collections.abc import Iterable
from dataclasses import replace
from pathlib import Path

import numpy as np

from offrow import datasets as datasets_mod
from offrow import synth as synth_mod
from offrow.learn.examples import (
    CHIP_DIR,
    DEFAULT_NEGATIVE_DIAMETER_M,
    Example,
    Manifest,
    centre_vegetation_fraction,
    cut_chip,
    example_id,
    load_chip,
    object_span_m,
    save_chip,
    split_for,
)

#: A negative chip's centre must be at least this far, in chip spans, from the
#: centre of every annotated box, so no labelled object leaks into it.
NEGATIVE_CLEARANCE_SPANS = 0.75

#: Centre vegetation fraction at or above which an unlabelled chip is "crop".
CROP_VEGETATION_FRACTION = 0.25

USU_LICENSE = "CC BY 4.0 (USU-Corn-WeedDB, Zenodo 20044178)"
SYNTH_LICENSE = "generated by offrow.synth; no external rights"
OPERATOR_LICENSE = "operator-owned; consent required before leaving the operator's account"


def _write(manifest: Manifest, chip: np.ndarray, example: Example) -> Example:
    save_chip(chip, manifest.chip_path(example))
    manifest.add(example)
    return example


# ---------------------------------------------------------------------------
# USU-Corn-WeedDB
# ---------------------------------------------------------------------------


def build_usu(
    root: Path,
    out_dir: Path,
    negatives_per_frame: int = 3,
    seed: int = 0,
    limit_frames: int | None = None,
) -> Manifest:
    """Examples from every annotated USU tile: the boxes, and clear ground between them."""
    dataset = datasets_mod.load_usu_corn_weeddb(Path(root))
    manifest = Manifest(Path(out_dir))
    rng = np.random.default_rng(seed)
    frames = dataset.frames[:limit_frames] if limit_frames else dataset.frames
    for frame in frames:
        image = frame.load()
        gsd_m = frame.gsd_mm / 1000.0
        group = frame.tile.source_id if frame.tile is not None else frame.image_path.stem
        split = split_for(f"usu:{group}")
        ref = str(frame.image_path.relative_to(Path(root)))
        boxes: list[tuple[float, float, float]] = []  # cx, cy, half span px
        for ann in frame.annotations:
            cx, cy = ann.centroid_px
            diameter = ann.equiv_diameter_m(frame.gsd_mm)
            span_m = object_span_m(diameter)
            span_px = int(round(span_m / gsd_m))
            chip, padded = cut_chip(image, cx, cy, span_px)
            eid = example_id(dataset.spec.key, ref, cx, cy, "weed")
            boxes.append((cx, cy, span_px / 2))
            _write(
                manifest,
                chip,
                Example(
                    id=eid,
                    source=dataset.spec.key,
                    source_ref=ref,
                    chip=f"{CHIP_DIR}/{eid}.png",
                    gsd_m=gsd_m,
                    span_m=span_px * gsd_m,
                    label="weed",
                    label_basis="annotated box (USU-Corn-WeedDB)",
                    group=group,
                    split=split,
                    crop=frame.crop,
                    growth_stage=frame.growth_stage,
                    species=ann.label,
                    diameter_m=diameter,
                    license=USU_LICENSE,
                    padded=padded,
                ),
            )
        for chip, cx, cy, basis, label in _negatives(image, gsd_m, boxes, negatives_per_frame, rng):
            eid = example_id(dataset.spec.key, ref, cx, cy, label)
            _write(
                manifest,
                chip,
                Example(
                    id=eid,
                    source=dataset.spec.key,
                    source_ref=ref,
                    chip=f"{CHIP_DIR}/{eid}.png",
                    gsd_m=gsd_m,
                    span_m=chip.shape[1] * gsd_m,
                    label=label,
                    label_basis=basis,
                    group=group,
                    split=split,
                    crop=frame.crop,
                    growth_stage=frame.growth_stage,
                    diameter_m=None,
                    license=USU_LICENSE,
                    padded=False,
                ),
            )
    manifest.write()
    return manifest


def _negatives(
    image: np.ndarray,
    gsd_m: float,
    boxes: list[tuple[float, float, float]],
    count: int,
    rng: np.random.Generator,
    attempts_per: int = 20,
) -> Iterable[tuple[np.ndarray, float, float, str, str]]:
    """Chips of clear ground in an exhaustively annotated frame, labelled by the mask."""
    h, w = image.shape[:2]
    span_px = int(round(object_span_m(DEFAULT_NEGATIVE_DIAMETER_M) / gsd_m))
    half = span_px / 2
    if span_px >= min(h, w):
        return
    clearance = NEGATIVE_CLEARANCE_SPANS * span_px
    found = 0
    for _ in range(count * attempts_per):
        if found >= count:
            break
        cx = rng.uniform(half, w - half)
        cy = rng.uniform(half, h - half)
        if any(math.hypot(cx - bx, cy - by) < clearance + bh for bx, by, bh in boxes):
            continue
        chip, _ = cut_chip(image, cx, cy, span_px)
        fraction = centre_vegetation_fraction(chip, gsd_m)
        if fraction >= CROP_VEGETATION_FRACTION:
            label, basis = (
                "crop",
                "derived: vegetation away from every annotated box (crop by mask)",
            )
        else:
            label, basis = (
                "other",
                "derived: ground away from every annotated box (not vegetation by mask)",
            )
        found += 1
        yield chip, cx, cy, basis, label


# ---------------------------------------------------------------------------
# Synthetic scenes
# ---------------------------------------------------------------------------

#: Weed sizes the synthetic source cycles through, so every diameter bin is
#: populated rather than only the 3 cm the flight spec defaults to.
SYNTH_WEED_DIAMETERS_M = (0.03, 0.06, 0.12, 0.25)
SYNTH_GSDS_MM = (5.5, 11.0, 22.0)


def scene_params_for(seed: int, acres: float = 0.25) -> synth_mod.SceneParams:
    """A varied scene per seed: size, confounders and row angle all move."""
    weed = SYNTH_WEED_DIAMETERS_M[seed % len(SYNTH_WEED_DIAMETERS_M)]
    return synth_mod.SceneParams(
        acres=acres,
        seed=seed,
        row_angle_deg=float((seed * 37) % 180),
        weed_diameter_m=weed,
        weed_diameter_max_m=max(0.10, weed * 2),
        shadows=seed % 2 == 0,
        wheel_tracks=seed % 3 == 0,
        wet_patches=seed % 4 == 0,
    )


def build_synth(
    out_dir: Path,
    seeds: Iterable[int] = range(24),
    gsds_mm: Iterable[float] = SYNTH_GSDS_MM,
    crop_per_scene: int = 40,
    other_per_scene: int = 30,
    weed_cap_per_scene: int = 120,
    acres: float = 0.25,
) -> Manifest:
    """Examples with exact truth, rendered natively at several resolutions."""
    manifest = Manifest(Path(out_dir))
    for seed in seeds:
        params = scene_params_for(seed, acres)
        scene = synth_mod.generate(params)
        group = f"synth:{seed}"
        split = split_for(group)
        rng = np.random.default_rng(seed)
        plant_xy = (
            np.concatenate([scene.crop_xy_m, scene.weed_xy_m])
            if len(scene.weed_xy_m)
            else scene.crop_xy_m
        )
        for gsd_mm in gsds_mm:
            gsd_m = gsd_mm / 1000.0
            image = synth_mod.render(scene, gsd_mm)
            ref = f"scene-{seed}@{gsd_mm:g}mm"
            weed_idx = np.arange(len(scene.weed_xy_m))
            if len(weed_idx) > weed_cap_per_scene:
                weed_idx = rng.choice(weed_idx, weed_cap_per_scene, replace=False)
            for i in weed_idx:
                x_m, y_m = scene.weed_xy_m[i]
                d = float(scene.weed_diameter_m[i])
                _synth_example(
                    manifest, image, gsd_m, x_m, y_m, d, "weed", ref, group, split, params
                )
            crop_idx = np.arange(len(scene.crop_xy_m))
            if len(crop_idx) > crop_per_scene:
                crop_idx = rng.choice(crop_idx, crop_per_scene, replace=False)
            for i in crop_idx:
                x_m, y_m = scene.crop_xy_m[i]
                d = float(scene.crop_diameter_m[i])
                _synth_example(
                    manifest, image, gsd_m, x_m, y_m, d, "crop", ref, group, split, params
                )
            for x_m, y_m in _clear_ground(
                scene.extent_m, plant_xy, other_per_scene, rng, clearance_m=0.20
            ):
                _synth_example(
                    manifest,
                    image,
                    gsd_m,
                    x_m,
                    y_m,
                    DEFAULT_NEGATIVE_DIAMETER_M,
                    "other",
                    ref,
                    group,
                    split,
                    params,
                )
    manifest.write()
    return manifest


def _synth_example(
    manifest, image, gsd_m, x_m, y_m, diameter_m, label, ref, group, split, params
) -> None:
    cx, cy = x_m / gsd_m, y_m / gsd_m
    span_px = int(round(object_span_m(diameter_m) / gsd_m))
    chip, padded = cut_chip(image, cx, cy, span_px)
    eid = example_id("synth", ref, cx, cy, label)
    basis = "synthetic truth" + (" (scene has shadows)" if params.shadows else "")
    _write(
        manifest,
        chip,
        Example(
            id=eid,
            source="synth",
            source_ref=ref,
            chip=f"{CHIP_DIR}/{eid}.png",
            gsd_m=gsd_m,
            span_m=span_px * gsd_m,
            label=label,
            label_basis=basis,
            group=group,
            split=split,
            crop="corn (synthetic)",
            growth_stage="V2-V6 (synthetic)",
            species="synthetic weed" if label == "weed" else None,
            diameter_m=diameter_m if label != "other" else None,
            license=SYNTH_LICENSE,
            padded=padded,
        ),
    )


def _clear_ground(
    extent_m,
    plant_xy: np.ndarray,
    count: int,
    rng: np.random.Generator,
    clearance_m: float,
    attempts_per: int = 30,
):
    """Points at least ``clearance_m`` from every plant, inside the field with a margin."""
    w, h = extent_m
    margin = object_span_m(DEFAULT_NEGATIVE_DIAMETER_M) / 2
    found = 0
    for _ in range(count * attempts_per):
        if found >= count:
            return
        x, y = rng.uniform(margin, w - margin), rng.uniform(margin, h - margin)
        if len(plant_xy) and np.min(np.hypot(plant_xy[:, 0] - x, plant_xy[:, 1] - y)) < clearance_m:
            continue
        found += 1
        yield x, y


# ---------------------------------------------------------------------------
# Operator verdicts
# ---------------------------------------------------------------------------

#: Columns pulled from weed_observations. The verdict is the label; the rest is provenance.
OBSERVATION_COLUMNS = (
    "id,user_id,field_id,scan_id,candidate_id,kind,verdict,verdict_source,species,crop,growth_stage,"
    "gsd_m,chip_gsd_m,chip_span_m,chip_path,area_m2,features,captured_at,pipeline_version,"
    "prediction,model_version,inference,finding_class,lat,lng"
)


def pull_verdicts(supabase_url: str, service_key: str, out_dir: Path) -> Path:
    """Export every observation with a verdict and a chip, plus the chips, to ``out_dir``.

    Needs the service role, because the archive is owner-scoped by RLS and this
    is a training export across every operator who has consented. Nothing here
    is called from the app; it runs on a machine that holds the key.
    """
    import requests

    out_dir = Path(out_dir)
    chips = out_dir / "raw"
    chips.mkdir(parents=True, exist_ok=True)
    headers = {"apikey": service_key, "Authorization": f"Bearer {service_key}"}
    rows: list[dict] = []
    offset = 0
    while True:
        r = requests.get(
            f"{supabase_url}/rest/v1/weed_observations",
            params={
                "select": OBSERVATION_COLUMNS,
                "verdict": "not.is.null",
                "chip_path": "not.is.null",
                "order": "created_at.asc",
                "offset": offset,
                "limit": 500,
            },
            headers=headers,
            timeout=60,
        )
        r.raise_for_status()
        page = r.json()
        rows.extend(page)
        if len(page) < 500:
            break
        offset += 500
    for row in rows:
        target = chips / f"{row['id']}.png"
        if target.exists():
            continue
        r = requests.get(
            f"{supabase_url}/storage/v1/object/weed-chips/{row['chip_path']}",
            headers=headers,
            timeout=60,
        )
        if r.ok:
            target.write_bytes(r.content)
        else:
            row["chip_missing"] = True
    export = out_dir / "observations.json"
    export.write_text(json.dumps(rows, indent=1))
    return export


def build_operator(export_dir: Path, out_dir: Path | None = None) -> Manifest:
    """Examples from an export written by :func:`pull_verdicts`."""
    export_dir = Path(export_dir)
    rows = json.loads((export_dir / "observations.json").read_text())
    manifest = Manifest(Path(out_dir) if out_dir else export_dir)
    for row in rows:
        raw = export_dir / "raw" / f"{row['id']}.png"
        if row.get("chip_missing") or not raw.exists() or not row.get("chip_span_m"):
            continue
        verdict = row.get("verdict")
        if verdict not in ("weed", "crop", "not_vegetation", "not_weed"):
            continue  # "unsure" teaches nothing
        image = load_chip(raw)
        png_px = max(image.shape[:2])
        span_m = float(row["chip_span_m"])
        gsd_m = span_m / png_px  # the stored PNG may be upscaled; its own GSD is span over pixels
        features = row.get("features") or {}
        diameter = features.get("equivDiameterM") if isinstance(features, dict) else None
        span_px = int(round(object_span_m(diameter or DEFAULT_NEGATIVE_DIAMETER_M) / gsd_m))
        chip, padded = cut_chip(image, image.shape[1] / 2, image.shape[0] / 2, min(span_px, png_px))
        if verdict == "weed":
            label, basis = "weed", "operator verdict: weed"
        elif verdict == "crop":
            label, basis = "crop", "operator verdict: crop"
        elif verdict == "not_vegetation":
            label, basis = "other", "operator verdict: not vegetation"
        else:
            veg = centre_vegetation_fraction(chip, gsd_m)
            label = "crop" if veg >= CROP_VEGETATION_FRACTION else "other"
            basis = f"operator verdict: not a weed; {label} by mask"
        group = f"field:{row.get('field_id') or row.get('user_id')}"
        eid = example_id("operator", row["id"], 0, 0, label)
        _write(
            manifest,
            chip,
            Example(
                id=eid,
                source="operator",
                source_ref=row["id"],
                chip=f"{CHIP_DIR}/{eid}.png",
                gsd_m=gsd_m,
                span_m=chip.shape[1] * gsd_m,
                label=label,
                label_basis=basis,
                group=group,
                split=split_for(group),
                crop=row.get("crop") or "",
                growth_stage=row.get("growth_stage") or "",
                species=row.get("species") if label == "weed" else None,
                diameter_m=diameter,
                license=OPERATOR_LICENSE,
                padded=padded,
            ),
        )
    manifest.write()
    return manifest


def relabel(manifest: Manifest, example_id_: str, label: str, basis: str) -> Manifest:
    """A reviewed correction. Returns a new manifest; the old file is untouched until written."""
    out = Manifest(manifest.directory)
    for e in manifest:
        out.add(replace(e, label=label, label_basis=basis) if e.id == example_id_ else e)
    return out
