import { useCallback, useEffect, useState } from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import { Loader2, Download, FileText, Grid3x3 } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import turfArea from "@turf/area";
import { polygon as turfPolygon } from "@turf/helpers";
import {
  type FarmerSettings, type LastFlownMission,
} from "@/lib/farmerSettings";
import { type AnalysisState, analysisStateOf, zoneAcres } from "@/lib/compareGround";
import { storageKey } from "@/lib/storage";
import {
  M2_PER_ACRE, fmtRate, fmtVolume, volumeToLitres, volumeUnit, volumeValue,
} from "@/lib/units";
import { useUnitSystem } from "@/hooks/useUnitSystem";
import {
  type ApplicationRecord, EMPTY_RECORD, WIND_DIRECTIONS,
  bannerFor, computedRateLPerAc, missingRecordFields, missionDateError,
  summariseZones, volumeZoneNote, zoneDetailCsv,
} from "@/lib/reportRecord";
import { reconcileReport } from "@/lib/reportReconcile";

// The report standardises on ACRES for every area it prints. fmtAreaAc
// elsewhere may drop to ft² for small areas, which is how one page came to say
// "0 ft²" beside "11.07 ac". One unit, one document.
const acres = (n: number) => `${n.toFixed(2)} ac`;

// Conversion now comes from lib/units.ts. The helpers that used to live here
// carried their own rounded constants — 0.264172 gal/L and an acre of 4047 m²
// against the defined 4046.8564224 — so a report and the planner could disagree
// about the same field by a few thousandths. One table, one answer.
const fmtVol = (litres: number, system: FarmerSettings["unit_system"], digits = 1) =>
  fmtVolume(litres, system ?? "imperial", digits).text;
const unitLabel = (system: FarmerSettings["unit_system"]) => volumeUnit(system ?? "imperial");

// ---- Real geodesic area for a ring of {lat,lng} points using turf.
// Turf expects GeoJSON [lng, lat] and a closed ring.
function ringAreaM2(ring: { lat: number; lng: number }[]): number {
  if (!ring || ring.length < 3) return 0;
  const coords = ring.map(p => [p.lng, p.lat] as [number, number]);
  const first = coords[0], last = coords[coords.length - 1];
  if (first[0] !== last[0] || first[1] !== last[1]) coords.push(first);
  try {
    return turfArea(turfPolygon([coords]));
  } catch {
    return 0;
  }
}
const M2_TO_AC = 1 / M2_PER_ACRE;   // exact, from lib/units.ts
const HA_TO_AC = 2.4710538147;

// Survives the Reports tab unmounting itself while it briefly switches to the
// Field tab to capture the map screenshot for the PDF.
const autoGeneratedFlightReports = new Set<string>();

type FieldRow = { id: string; name: string; boundary_area_hectares: number | null };
type TaskRow = { id: string; created_at: string };
type DroneRow = { id: string; name: string; model: string; battery: number };
type FlightLogRow = LastFlownMission;
type ReportRow = {
  id: string; generated_at: string; pilot_name: string | null;
  storage_path: string; summary: any;
};

function newestMission(...logs: Array<FlightLogRow | null | undefined>): FlightLogRow | null {
  const valid = logs.filter(Boolean) as FlightLogRow[];
  if (!valid.length) return null;
  return valid.sort((a, b) => {
    const at = new Date(a.created_at ?? a.date_flown).getTime();
    const bt = new Date(b.created_at ?? b.date_flown).getTime();
    return bt - at;
  })[0];
}

type Props = {
  field: FieldRow | null;
  task: TaskRow;
  settings: FarmerSettings;
  activeDrone: DroneRow | null;
  lastLog: FlightLogRow | null;
  // Switches viewer to a given tab key; we use it to flash Field View for capture.
  setActiveTab: (k: "field" | "weather" | "treatment" | "planner" | "reports" | "settings") => void;
  /**
   * Puts Field View into report-capture layers (orthomosaic + boundary +
   * treatment-grid zones ONLY) and back. The captured map must be driven by
   * the same data as the report's tables, or the two can contradict each
   * other on one page.
   */
  prepareMapCapture: () => void;
  restoreMapCapture: () => void;
};

export default function ReportsTab({
  field, task, settings, activeDrone, lastLog, setActiveTab,
  prepareMapCapture, restoreMapCapture,
}: Props) {
  const [pilotName, setPilotName] = useState<string>(() => localStorage.getItem(storageKey("pilot_name")) ?? "");
  const [generating, setGenerating] = useState(false);
  // Per-zone detail is an appendix a reader opts into, never the main body.
  const [includeAppendix, setIncludeAppendix] = useState(false);
  const [reports, setReports] = useState<ReportRow[]>([]);
  const [fetchedLastLog, setFetchedLastLog] = useState<FlightLogRow | null>(null);

  // The scan's assessment, fresh from the row: the treatment grid snapshots
  // zones there on every save (lib/scanAssessment.ts), and results left by the
  // retired vision path surface as source "legacy" — labelled, never blended.
  const [assessment, setAssessment] = useState<AnalysisState>({ kind: "none" });
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const { data } = await supabase.from("odm_tasks")
        .select("ai_analysis, ai_analysis_at").eq("id", task.id).maybeSingle();
      if (cancelled) return;
      setAssessment(analysisStateOf({
        ai_analysis: data?.ai_analysis ?? null,
        ai_analysis_at: (data?.ai_analysis_at as string | null) ?? null,
      }));
    })();
    return () => { cancelled = true; };
  }, [task.id]);

  // ---- Editable mission fields. Prefilled from the last logged flight when
  //      available, but always overridable so the pilot can double-check / fix
  //      numbers before the report is generated.
  const [missionDate, setMissionDate] = useState<string>("");
  const [battStartIn, setBattStartIn] = useState<string>("");
  const [battEndIn, setBattEndIn] = useState<string>("");
  const [refillsIn, setRefillsIn] = useState<string>("");
  const [litersIn, setLitersIn] = useState<string>("");
  const [notesIn, setNotesIn] = useState<string>("");

  // Site-wide preference, not the per-field one: a report opened from the
  // Fields list should read the same as one opened from a scan.
  const unit = useUnitSystem();
  const isImperial = unit === "imperial";

  // ONLY missions flown against THIS scan count. The report used to adopt the
  // field's newest log whatever scan it belonged to, which is how a page could
  // print "Zones flown 0/0" beside "Volume applied 3.3 gal": the volume came
  // from a different mission entirely.
  const forThisScan = (l: FlightLogRow | null | undefined) =>
    l && l.scan_id === task.id ? l : null;
  // A flight flown against ANOTHER scan of this field is offered, never
  // adopted: silently pulling its numbers in is the contradiction above, but
  // hiding it means an operator who logged from a different scan's workspace
  // sees an empty report and no explanation. So it is shown, named, and
  // attached only if they say so.
  const [adoptedLog, setAdoptedLog] = useState<FlightLogRow | null>(null);
  const [otherFlights, setOtherFlights] = useState<FlightLogRow[]>([]);
  const effectiveLastLog = newestMission(
    forThisScan(fetchedLastLog), forThisScan(lastLog), forThisScan(settings.last_flown_mission),
  ) ?? adoptedLog;
  const effectiveFlightLogId = effectiveLastLog?.source === "field_snapshot" ? null : (effectiveLastLog?.id ?? null);
  const effectiveMissionRecordId = effectiveLastLog?.id ?? null;

  // Reports owns its own latest-log lookup, scoped to this scan.
  useEffect(() => {
    if (!field?.id) return;
    let cancelled = false;
    (async () => {
      const { data, error } = await supabase
        .from("flight_logs")
        .select("id, field_id, scan_id, drone_id, date_flown, battery_start, battery_end, tank_refills, zones_completed, acres_treated, liters_applied, notes, created_at")
        .eq("field_id", field.id)
        .eq("scan_id", task.id)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      if (cancelled) return;
      if (error) console.warn("[ReportsTab] latest flight log lookup failed", error);
      setFetchedLastLog(data ? ({ ...(data as FlightLogRow), source: "flight_logs" }) : null);

      // Nothing logged against this scan: find the field's other recent
      // flights so the operator can attach one instead of facing a blank form
      // with no hint that their mission exists.
      if (!data) {
        const { data: others } = await supabase
          .from("flight_logs")
          .select("id, field_id, scan_id, drone_id, date_flown, battery_start, battery_end, tank_refills, zones_completed, acres_treated, liters_applied, notes, created_at")
          .eq("field_id", field.id)
          .order("date_flown", { ascending: false })
          .limit(3);
        if (!cancelled) {
          setOtherFlights(
            ((others as FlightLogRow[] | null) ?? []).filter(l => l.scan_id !== task.id),
          );
        }
      } else if (!cancelled) {
        setOtherFlights([]);
      }
    })();
    return () => { cancelled = true; };
  }, [field?.id, task.id]);

  // Attaching is per-scan and never sticky across scans.
  useEffect(() => { setAdoptedLog(null); }, [task.id]);

  // The application record: prefilled from the mission log's record (entered
  // in the Log Flight dialog), then the field's stored defaults, and editable
  // here so an older mission's gaps can be corrected before generating.
  const [record, setRecord] = useState<ApplicationRecord>(EMPTY_RECORD);
  useEffect(() => {
    // The per-mission record (times, wind, temperature) has NO column in
    // flight_logs — it lives only on the settings snapshot of the same
    // mission. When the database row wins the "which log" pick, reading
    // `.record` off it finds nothing, and the operator watched their logged
    // wind and temperature fail to prefill while the Flight Log tab happily
    // displayed them. So: take the record from whichever carrier of THIS
    // mission actually has it, matched by id.
    const snap = settings.last_flown_mission;
    const fromLog = effectiveLastLog?.record
      ?? (effectiveLastLog && snap?.id === effectiveLastLog.id ? snap.record : null);
    const defaults = settings.application_record;
    setRecord({
      ...EMPTY_RECORD,
      ...(defaults ?? {}),
      ...(fromLog ?? {}),
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [effectiveLastLog?.id, settings.last_flown_mission?.id]);

  // Whenever the logged-flight backing data changes, re-prefill the editable
  // fields. Pilot can still type over any of them.
  useEffect(() => {
    setMissionDate(effectiveLastLog?.date_flown ?? "");
    setBattStartIn(effectiveLastLog?.battery_start != null ? String(effectiveLastLog.battery_start) : "");
    setBattEndIn(effectiveLastLog?.battery_end != null ? String(effectiveLastLog.battery_end) : "");
    setRefillsIn(effectiveLastLog?.tank_refills != null ? String(effectiveLastLog.tank_refills) : "0");
    setLitersIn(
      effectiveLastLog?.liters_applied != null
        ? String(+volumeValue(Number(effectiveLastLog.liters_applied), unit).toFixed(2))
        : ""
    );
    setNotesIn(effectiveLastLog?.notes ?? "");
  }, [effectiveLastLog?.id, effectiveLastLog?.date_flown, effectiveLastLog?.battery_start, effectiveLastLog?.battery_end,
      effectiveLastLog?.tank_refills, effectiveLastLog?.liters_applied, effectiveLastLog?.notes, isImperial]);

  const loadReports = useCallback(async () => {
    if (!field?.id) return;
    const { data } = await supabase
      .from("field_reports")
      .select("id, generated_at, pilot_name, storage_path, summary")
      .eq("field_id", field.id)
      .order("generated_at", { ascending: false });
    setReports((data as ReportRow[] | null) ?? []);
  }, [field?.id]);
  useEffect(() => { void loadReports(); }, [loadReports]);

  useEffect(() => {
    localStorage.setItem(storageKey("pilot_name"), pilotName);
  }, [pilotName]);

  // ---- Derived values (zones, chemical totals, savings) ----
  // Analysis is tri-valent in the product (never ran / ran clean / has zones);
  // Every computed claim below is gated on the assessment's state, decided in
  // analysisStateOf: no assessment → no numbers; a legacy-path result is shown
  // but labelled and never given the grid's styling or chemical arithmetic.
  const isDone = assessment.kind === "done";
  const source: "grid" | "legacy" | null = isDone ? assessment.source : null;
  const hasGridAssessment = isDone && source === "grid";
  const zones = isDone ? assessment.zones : [];
  const zoneRows = zones.map((z, i) => {
    const zz = z as {
      id?: string; ring?: { lat: number; lng: number }[]; areaM2?: number;
      rateLha?: number; issue?: string; name?: string;
    };
    const flown = !!zz.id && !!effectiveLastLog?.zones_completed?.includes(zz.id);
    return {
      id: zz.id ?? `zone-${i}`,
      // Grid zones are described by the operator's classification; legacy
      // zones carried a model-written name.
      name: zz.name ?? zz.issue ?? "Unclassified",
      issue: zz.issue ?? (source === "legacy" ? "" : "Unclassified"),
      // Grid snapshots carry the summed clipped cell area (the priced number);
      // legacy zones only have their ring.
      acres: zoneAcres(zz),
      rateLha: typeof zz.rateLha === "number" ? zz.rateLha : null,
      areaM2: typeof zz.areaM2 === "number" ? zz.areaM2 : ringAreaM2(zz.ring ?? []),
      flown,
    };
  });

  const fieldAcres = field?.boundary_area_hectares != null
    ? field.boundary_area_hectares * HA_TO_AC : 0;
  const treatedAcres = zoneRows.reduce((s, z) => s + z.acres, 0);

  // Planned chemical: the grid's OWN arithmetic — Σ(cell area × painted rate)
  // per zone, bucketed by the operator's classification. Real rates the
  // operator chose, not a hardcoded default; computed only for grid
  // assessments, never for legacy results.
  type Bucket = { label: string; litres: number };
  const buckets = new Map<string, Bucket>();
  if (hasGridAssessment) {
    for (const z of zoneRows) {
      if (z.rateLha == null || z.rateLha <= 0) continue;
      const litres = (z.areaM2 / 10_000) * z.rateLha;
      const label = z.issue || "Unclassified";
      const prev = buckets.get(label);
      if (prev) prev.litres += litres;
      else buckets.set(label, { label, litres });
    }
  }
  const totalLitres = [...buckets.values()].reduce((s, b) => s + b.litres, 0);
  // Savings are stated against a NAMED baseline: the whole field at the
  // operator's configured medium rate. A baseline nobody chose is a number
  // nobody can defend.
  const baselineRateLha = settings.spray_rates_lha.medium;
  const fullFieldLitres = (fieldAcres * M2_PER_ACRE / 10_000) * baselineRateLha;
  const savingsPct = hasGridAssessment && fullFieldLitres > 0
    ? Math.max(0, Math.min(100, Math.round((1 - totalLitres / fullFieldLitres) * 100)))
    : 0;

  // Pre-flight vs post-flight framing.
  // Post-flight = a mission has been logged for THIS scan.
  const isPostFlight = !!effectiveLastLog;
  const targetedAcres = isPostFlight
    ? zoneRows.filter(z => z.flown).reduce((s, z) => s + z.acres, 0)
    : treatedAcres;

  // The grower-facing zone summary: grouped by classification × rate, with
  // the per-zone detail relegated to the appendix and CSV.
  const zoneSummary = summariseZones(
    zoneRows.map(z => ({
      id: z.id, issue: z.issue, acres: z.acres, rateLha: z.rateLha, flown: z.flown,
    })),
    fieldAcres,
  );


  // ---- Mission stats from the editable inputs (prefilled from last log). ----
  const numOrNull = (s: string) => {
    const t = s.trim(); if (!t) return null;
    const n = Number(t); return Number.isFinite(n) ? n : null;
  };
  const battStart = numOrNull(battStartIn);
  const battEnd = numOrNull(battEndIn);
  const tankRefills = numOrNull(refillsIn) ?? 0;
  // The "Volume applied" input is shown in whichever units the user picked,
  // but everything downstream (DB row, PDF math) is normalised back to L.
  const volumeAppliedRaw = numOrNull(litersIn);
  const litersApplied = volumeAppliedRaw == null
    ? null
    : volumeToLitres(volumeAppliedRaw, unit);
  const pilotNotes = notesIn;

  // ---- The record's completeness decides DRAFT vs FINAL. --------------------
  // A report missing required record fields still generates — an operator in
  // the field should never be locked out of their own document — but it
  // carries a DRAFT — INCOMPLETE watermark on every page and each gap renders
  // labelled in red, never silently dropped.
  // A legacy-only result does not make a report FINAL: the record needs a
  // treatment-grid assessment, which is also the nudge that migrates old
  // scans onto the real analysis path.
  const missing = missingRecordFields({
    hasAnalysis: hasGridAssessment,
    fieldAcres,
    volumeAppliedL: litersApplied,
    missionLogged: !!effectiveLastLog,
    record,
  });
  const isDraft = missing.length > 0;
  const dateErr = missionDate ? missionDateError(missionDate) : null;
  const zonesFlownCount = zoneRows.filter(z => z.flown).length;
  const volumeNote = volumeZoneNote({
    volumeAppliedL: litersApplied,
    zonesFlown: zonesFlownCount,
    zonesTotal: zoneRows.length,
    hasAnalysis: isDone,
  });
  const acresTreatedLogged = effectiveLastLog?.acres_treated ?? null;
  const rateLPerAc = computedRateLPerAc(litersApplied, acresTreatedLogged);

  // The one banner the report shows, decided in lib/reportRecord so the states
  // cannot blur: "no assessment" is neutral and explicitly not a finding;
  // success styling exists only for a grid assessment with marked zones. The
  // post-flight savings figure is rate-weighted, so the banner carries the two
  // volumes it is computed from — the page must let a reader reproduce it.
  const banner = bannerFor({
    hasAnalysis: isDone,
    source: source ?? undefined,
    zoneCount: zoneRows.length,
    targetedAcres: isDone && source === "legacy" ? treatedAcres : targetedAcres,
    fieldAcres,
    isPostFlight,
    savingsPct,
    chemical: hasGridAssessment && fullFieldLitres > 0
      ? {
          planned: fmtVol(totalLitres, unit),
          fullField: fmtVol(fullFieldLitres, unit),
          baselineRate: fmtRate(baselineRateLha, unit).text,
          // Once a volume is LOGGED, the claim rests on it, not the plan.
          applied: litersApplied != null ? fmtVol(litersApplied, unit) : null,
          appliedSavingsPct: litersApplied != null
            ? Math.max(0, Math.round((1 - litersApplied / fullFieldLitres) * 100))
            : null,
          exceededBaseline: litersApplied != null && litersApplied >= fullFieldLitres,
        }
      : undefined,
  });

  // ---- Reconcile before printing. -------------------------------------------
  // Every derived figure compared against every other; findings print in the
  // body, never block, and never silently pick between conflicting numbers.
  const reconciliations = reconcileReport({
    plannedL: hasGridAssessment ? totalLitres : null,
    appliedL: litersApplied,
    baselineLha: baselineRateLha,
    computedRateLPerAc: rateLPerAc,
    markedAcres: hasGridAssessment ? zoneSummary.totals.treatedAcres : null,
    loggedTreatedAcres: acresTreatedLogged,
    zonesFlown: zonesFlownCount,
    zonesTotal: zoneRows.length,
    windMph: record.wind_speed_mph,
    tempF: record.temperature_f,
    startTime: record.start_time,
    endTime: record.end_time,
    fmtVolume: (l) => fmtVol(l, unit),
    fmtAcres: (ac2) => acres(ac2),
    fmtRatePerAc: (lPerAc) => `${fmtVol(lPerAc, unit, 2)}/ac`,
  });

  // ---- PDF generation ----
  const generate = async () => {
    if (!field) { toast.error("Define a field boundary first."); return; }
    if (!pilotName.trim()) { toast.error("Enter a pilot name first."); return; }
    if (!missionDate) { toast.error("Enter the mission date first."); return; }
    // A mission date after the report date is invalid input, not a draft state:
    // nothing downstream can be right, so this one blocks outright.
    const dateProblem = missionDateError(missionDate);
    if (dateProblem) { toast.error(dateProblem); return; }
    setGenerating(true);
    let restored = false;
    const capRoot = document.getElementById("field-view-capture");
    const prevVisibility = capRoot?.style.visibility ?? "";
    const prevPointer = capRoot?.style.pointerEvents ?? "";
    try {
      // 1) Make sure the map is on-screen for html2canvas, showing EXACTLY the
      //    layers the report's tables describe — orthomosaic, boundary, AI
      //    zones — and none of the operator's working overlays. The map and
      //    the tables must be driven by the same data or they can disagree.
      prepareMapCapture();
      setActiveTab("field");
      await new Promise(r => setTimeout(r, 50));
      if (capRoot) {
        capRoot.style.visibility = "visible";
        capRoot.style.pointerEvents = "none";
      }
      // Wait for tiles to settle.
      await new Promise(r => setTimeout(r, 900));

      let mapDataUrl: string | null = null;
      const mapEl = capRoot?.querySelector(".leaflet-container") as HTMLElement | null;
      if (mapEl) {
        try {
          const canvas = await html2canvas(mapEl, {
            useCORS: true, allowTaint: false, backgroundColor: "#0a0a0a",
            logging: false, scale: 1.5,
          });
          mapDataUrl = canvas.toDataURL("image/jpeg", 0.85);
        } catch (err) {
          console.warn("map capture failed", err);
        }
      }

      // 2) Restore Reports tab and any hidden state.
      if (capRoot) {
        capRoot.style.visibility = prevVisibility;
        capRoot.style.pointerEvents = prevPointer;
      }
      restoreMapCapture();
      setActiveTab("reports");
      restored = true;

      // 3) Build the PDF.
      const pdf = new jsPDF({ unit: "pt", format: "letter" });
      const W = pdf.internal.pageSize.getWidth();
      const H = pdf.internal.pageSize.getHeight();
      const M = 36;
      let y = M;

      // ---- Pagination -----------------------------------------------------
      // Content flows through `ensure(need)`: anything that will not fit above
      // the reserved footer band starts a new page with a compact continuation
      // header. Nothing is ever drawn past BOTTOM, so the footer can never
      // overprint a table row and no section can silently fall off the page —
      // a real report once pushed the entire application record into the void
      // below y=792 this way.
      const FOOTER_H = 48;
      const BOTTOM = H - FOOTER_H;
      const contHeader = () => {
        pdf.setFont("helvetica", "bold"); pdf.setTextColor(76, 175, 80); pdf.setFontSize(10);
        pdf.text("SwathWise", M, y);
        pdf.setFont("helvetica", "normal"); pdf.setTextColor(120); pdf.setFontSize(8);
        pdf.text(`Field Spray & Application Report · ${field.name} (continued)`, W - M, y, { align: "right" });
        y += 6;
        pdf.setDrawColor(220); pdf.setLineWidth(0.5); pdf.line(M, y, W - M, y);
        y += 14;
      };
      const newPage = () => { pdf.addPage(); y = M; contHeader(); };
      const ensure = (need: number) => { if (y + need > BOTTOM) newPage(); };
      const today = new Date();
      const ymd = today.toISOString().slice(0, 10);
      const niceDate = today.toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
      const scanDate = new Date(task.created_at).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
      const missionDateNice = missionDate
        ? new Date(missionDate + "T00:00").toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })
        : "-";

      // Every string below reaches a GROWER, not the app operator. Nothing on
      // this document may read as an in-app instruction, and any required value
      // that is absent renders as a labelled red MISSING — never silently
      // dropped, never defaulted.
      const MISSING_RGB: [number, number, number] = [220, 53, 69];
      const kvRow = (label: string, value: string | null, x: number, valueX: number, yy: number) => {
        pdf.setFont("helvetica", "bold"); pdf.setTextColor(110); pdf.setFontSize(8);
        pdf.text(label, x, yy);
        if (value) {
          pdf.setFont("helvetica", "normal"); pdf.setTextColor(20); pdf.setFontSize(10);
          pdf.text(value, valueX, yy);
        } else {
          pdf.setFont("helvetica", "bold");
          pdf.setTextColor(MISSING_RGB[0], MISSING_RGB[1], MISSING_RGB[2]);
          pdf.setFontSize(9);
          pdf.text("MISSING", valueX, yy);
        }
      };
      const has = (s: string | null | undefined) => (s && s.trim() ? s.trim() : null);

      // Header: brand + generation date
      pdf.setFont("helvetica", "bold"); pdf.setTextColor(76, 175, 80);
      pdf.setFontSize(16); pdf.text("SwathWise", M, y);
      pdf.setFont("helvetica", "normal"); pdf.setTextColor(120);
      pdf.setFontSize(9); pdf.text(`Generated ${niceDate}`, W - M, y, { align: "right" });
      y += 8;
      pdf.setDrawColor(220); pdf.setLineWidth(0.5); pdf.line(M, y, W - M, y);
      y += 16;
      pdf.setFont("helvetica", "bold"); pdf.setTextColor(30);
      pdf.setFontSize(17); pdf.text("FIELD SPRAY & APPLICATION REPORT", M, y);
      y += 14;
      // Field identity line
      pdf.setFont("helvetica", "normal"); pdf.setTextColor(90); pdf.setFontSize(10);
      pdf.text(
        `${field.name} · ${settings.crop_type ? settings.crop_type.replace(/_/g, " ") : "crop not set"} · ${fieldAcres > 0 ? acres(fieldAcres) : "boundary not set"}`,
        M, y,
      );
      y += 12;
      if (isDraft) {
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(MISSING_RGB[0], MISSING_RGB[1], MISSING_RGB[2]);
        pdf.setFontSize(8);
        const draftLine = pdf.splitTextToSize(
          `DRAFT — INCOMPLETE. Missing: ${missing.join(", ")}.`, W - 2 * M,
        );
        pdf.text(draftLine, M, y);
        y += draftLine.length * 9 + 4;
      }
      y += 2;

      // Metadata grid, two columns; all areas in acres.
      const metaL: [string, string | null][] = [
        ["FIELD", field.name],
        ["TOTAL AREA", fieldAcres > 0 ? acres(fieldAcres) : null],
        ["SCAN DATE", scanDate],
        ["MISSION DATE", missionDateNice],
      ];
      const metaR: [string, string | null][] = [
        ["CROP", has(settings.crop_type?.replace(/_/g, " ")) ?? null],
        ["PILOT", has(pilotName)],
        ["AIRCRAFT", activeDrone ? `${activeDrone.name} · ${activeDrone.model}` : "Not recorded"],
        ["REPORT DATE", niceDate],
      ];
      const colHalf = (W - 2 * M) / 2;
      for (let i = 0; i < Math.max(metaL.length, metaR.length); i++) {
        if (metaL[i]) kvRow(metaL[i][0], metaL[i][1], M, M + 70, y);
        if (metaR[i]) kvRow(metaR[i][0], metaR[i][1], M + colHalf + 6, M + colHalf + 76, y);
        y += 13;
      }
      y += 4;
      pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;

      // Field map — captured from the same layers the tables below describe.
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(110);
      pdf.text("FIELD MAP", M, y); y += 8;
      if (mapDataUrl) {
        const imgW = W - 2 * M;
        const imgH = imgW * 0.38;
        pdf.addImage(mapDataUrl, "JPEG", M, y, imgW, imgH);
        y += imgH + 4;
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(7); pdf.setTextColor(150);
        pdf.text(
          hasGridAssessment && zoneRows.length > 0
            ? "Framed to the flown area: orthomosaic, field boundary, and the treatment-grid zones summarised below. Surrounding basemap is outside the flight."
            : "Framed to the flown area: orthomosaic and field boundary; surrounding basemap is outside the flight. No treatment zones are drawn because none were marked.",
          M, y,
        );
        y += 10;
      } else {
        pdf.setFontSize(9); pdf.setTextColor(150);
        pdf.text("Map image not available for this report.", M, y + 4);
        y += 20;
      }
      pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;

      // Result banner. Four states that must never share a visual treatment:
      //   no assessment → neutral outline, explicitly NOT a finding of zero
      //   legacy result → amber outline, named as the retired path's output
      //   clean         → quiet informational state, worded as a real result
      //   zones         → the only state that earns the green success fill
      const bannerH = banner.note ? 58 : 48;
      if (banner.tone === "success") {
        pdf.setFillColor(76, 175, 80);
        pdf.roundedRect(M, y, W - 2 * M, bannerH, 6, 6, "F");
        pdf.setTextColor(255);
      } else {
        const stroke: [number, number, number] =
          banner.tone === "clean" ? [76, 175, 80]
          : banner.tone === "legacy" ? [217, 119, 6]
          : [160, 160, 160];
        const ink: [number, number, number] =
          banner.tone === "clean" ? [46, 125, 50]
          : banner.tone === "legacy" ? [180, 83, 9]
          : [90, 90, 90];
        pdf.setDrawColor(stroke[0], stroke[1], stroke[2]);
        pdf.setLineWidth(1);
        pdf.roundedRect(M, y, W - 2 * M, bannerH, 6, 6, "S");
        pdf.setTextColor(ink[0], ink[1], ink[2]);
      }
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(14);
      pdf.text(banner.big, M + 14, y + 22);
      pdf.setFontSize(9); pdf.setFont("helvetica", "normal");
      pdf.text(banner.sub, M + 14, y + 36);
      if (banner.note) {
        pdf.setFont("helvetica", "bold"); pdf.setFontSize(8);
        pdf.text(banner.note, M + 14, y + 49);
      }
      y += bannerH + 12;

      // RECONCILIATION NOTES — in the body, right under the headline, never
      // fine print. When the document's own figures disagree, the document
      // says so before a reader who did not fly the mission can be misled by
      // either number. Nothing is blocked and no conflicting number is
      // quietly dropped.
      if (reconciliations.length > 0) {
        pdf.setFont("helvetica", "bold"); pdf.setFontSize(9);
        pdf.setTextColor(180, 83, 9);
        ensure(16);
        pdf.text("RECONCILIATION NOTES", M, y); y += 11;
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(8.5);
        for (const r of reconciliations) {
          const wrapped = pdf.splitTextToSize(`• ${r.message}`, W - 2 * M - 6);
          ensure(wrapped.length * 10 + 4);
          pdf.setTextColor(146, 64, 14);
          pdf.text(wrapped, M + 3, y);
          y += wrapped.length * 10 + 4;
        }
        y += 4;
        pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;
      }

      // Treatment zones
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(110);
      pdf.text("TREATMENT ZONES", M, y); y += 11;
      pdf.setFontSize(10); pdf.setFont("helvetica", "normal");
      if (!isDone) {
        pdf.setTextColor(MISSING_RGB[0], MISSING_RGB[1], MISSING_RGB[2]);
        pdf.setFontSize(9);
        pdf.text("Not determined — this scan has no treatment-grid assessment.", M, y); y += 14;
      } else if (zoneRows.length === 0) {
        pdf.setTextColor(90);
        pdf.setFontSize(9);
        pdf.text(
          source === "legacy"
            ? "The legacy analysis on file recorded no zones."
            : "The assessment marked no ground for targeted treatment.",
          M, y,
        ); y += 14;
      } else {
        if (source === "legacy") {
          pdf.setFont("helvetica", "bold");
          pdf.setTextColor(180, 83, 9);
          pdf.setFontSize(8);
          pdf.text("Recorded by the retired vision-analysis system — not a treatment-grid assessment.", M, y);
          y += 11;
          pdf.setFont("helvetica", "normal");
        }
        // GROUPED, not enumerated. The grid legitimately yields dozens of
        // small contiguous zones; a grower reads classification × rate, not
        // the lattice. Per-zone detail lives in the appendix and the CSV.
        if (zoneSummary.allUnclassified) {
          pdf.setFont("helvetica", "bold"); pdf.setTextColor(180, 83, 9); pdf.setFontSize(8);
          pdf.text(
            "Zones have not been classified. Areas and rates below are as painted; add classifications in the Treatment Grid.",
            M, y,
          );
          y += 11;
        }
        // Column header
        const COL = { rate: W - M - 250, area: W - M - 150, zones: W - M - 80, flown: W - M };
        pdf.setFont("helvetica", "bold"); pdf.setTextColor(140); pdf.setFontSize(7.5);
        pdf.text("CLASSIFICATION", M, y);
        pdf.text("RATE", COL.rate, y, { align: "right" });
        pdf.text("AREA", COL.area, y, { align: "right" });
        pdf.text("ZONES", COL.zones, y, { align: "right" });
        pdf.text("FLOWN", COL.flown, y, { align: "right" });
        y += 4;
        pdf.setDrawColor(230); pdf.line(M, y, W - M, y);
        y += 10;
        for (const g of zoneSummary.groups) {
          ensure(14);
          pdf.setFont("helvetica", "bold"); pdf.setTextColor(30); pdf.setFontSize(9.5);
          pdf.text(g.label, M, y);
          pdf.setFont("helvetica", "normal"); pdf.setTextColor(70);
          pdf.text(g.rateLha != null ? fmtRate(g.rateLha, unit).text : "—", COL.rate, y, { align: "right" });
          pdf.setTextColor(30);
          pdf.text(acres(g.acres), COL.area, y, { align: "right" });
          pdf.setTextColor(70);
          pdf.text(String(g.count), COL.zones, y, { align: "right" });
          if (g.flownState === "all") {
            pdf.setFont("helvetica", "bold"); pdf.setTextColor(34, 139, 34);
            pdf.text("Flown", COL.flown, y, { align: "right" });
          } else if (g.flownState === "partial") {
            pdf.setFont("helvetica", "normal"); pdf.setTextColor(180, 83, 9);
            pdf.text(`${g.flownCount}/${g.count}`, COL.flown, y, { align: "right" });
          } else {
            pdf.setFont("helvetica", "normal"); pdf.setTextColor(150);
            pdf.text("Not flown", COL.flown, y, { align: "right" });
          }
          y += 13;
        }
        // Totals: the row that lets a reader tie the banner back to acres.
        ensure(30);
        pdf.setDrawColor(200); pdf.line(M, y - 4, W - M, y - 4);
        pdf.setFont("helvetica", "bold"); pdf.setTextColor(30); pdf.setFontSize(9.5);
        pdf.text("Marked for treatment (grid)", M, y);
        pdf.text(acres(zoneSummary.totals.treatedAcres), COL.area, y, { align: "right" });
        pdf.text(String(zoneSummary.totals.zoneCount), COL.zones, y, { align: "right" });
        pdf.text(`${zoneSummary.totals.flownCount}/${zoneSummary.totals.zoneCount}`, COL.flown, y, { align: "right" });
        y += 12;
        pdf.setFont("helvetica", "normal"); pdf.setTextColor(90); pdf.setFontSize(9);
        pdf.text("Untreated", M, y);
        pdf.text(acres(zoneSummary.totals.untreatedAcres), COL.area, y, { align: "right" });
        y += 12;
        pdf.text("Field total", M, y);
        pdf.text(acres(zoneSummary.totals.fieldAcres), COL.area, y, { align: "right" });
        y += 13;
      }
      y += 4;
      pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;

      // Planned chemical use — the grid's own arithmetic: Σ(cell area ×
      // painted rate) per zone. Real operator-chosen rates, kept apart from
      // the logged volume below; never computed from a legacy result.
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(110);
      pdf.text("PLANNED CHEMICAL USE (FROM GRID RATES)", M, y); y += 11;
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(10);
      if (!hasGridAssessment || buckets.size === 0) {
        pdf.setTextColor(90); pdf.setFontSize(9);
        pdf.text(
          hasGridAssessment
            ? "Not computed — no treatment zones to plan against."
            : source === "legacy"
              ? "Not computed — the legacy result carries no grid rates. Re-assess with the treatment grid."
              : "Not computed — treatment zones were not determined.",
          M, y,
        );
        y += 14;
      } else {
        for (const b of buckets.values()) {
          ensure(14);
          pdf.setTextColor(30); pdf.text(b.label, M, y);
          pdf.text(fmtVol(b.litres, unit), W - M, y, { align: "right" });
          y += 13;
        }
        ensure(42);
        pdf.setDrawColor(235); pdf.line(M, y - 4, W - M, y - 4);
        pdf.setFont("helvetica", "bold");
        pdf.text("Planned total", M, y);
        pdf.text(fmtVol(totalLitres, unit), W - M, y, { align: "right" });
        y += 13;
        // The savings line prints BOTH volumes: 1 − planned/baseline is the
        // banner's percentage, reproducible with the numbers on this page.
        pdf.setFont("helvetica", "normal"); pdf.setTextColor(90); pdf.setFontSize(9);
        pdf.text(`Whole field at ${fmtRate(baselineRateLha, unit).text} (your medium rate)`, M, y);
        pdf.text(fmtVol(fullFieldLitres, unit), W - M, y, { align: "right" });
        y += 12;
        pdf.setTextColor(76, 175, 80);
        pdf.text("Saved vs that baseline (rate-weighted)", M, y);
        pdf.text(`${savingsPct}%`, W - M, y, { align: "right" });
        y += 14;
      }
      pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;

      // APPLICATION RECORD — the section that makes this a pesticide
      // application record rather than a summary. It ALWAYS renders, whatever
      // came before it: the space it needs is reserved as a block, so a long
      // zone table can push it to the next page but never off the document.
      ensure(9 * 13 + 30);
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(110);
      pdf.text("APPLICATION RECORD", M, y); y += 11;
      const recL: [string, string | null][] = [
        ["GROWER / CUSTOMER", has(record.grower_name)],
        ["PRODUCT", has(record.product_name)],
        ["EPA REG. NO.", has(record.epa_reg_no)],
        ["APPLICATION DATE", missionDateNice],
        ["START TIME", record.start_time],
        ["END TIME", record.end_time],
        ["VOLUME APPLIED", litersApplied != null ? fmtVol(litersApplied, unit) : null],
      ];
      // TWO area definitions exist on this document and are never mixed:
      // "marked (grid)" is the grid's cell arithmetic in the zones table;
      // "treated (logged)" is the pilot's flight log, and it alone feeds the
      // computed rate. Each is labelled as itself wherever it appears.
      const recR: [string, string | null][] = [
        ["RATE (COMPUTED)", rateLPerAc != null
          ? `${fmtVol(rateLPerAc, unit, 2)}/ac (logged volume ÷ logged treated area)` : null],
        ["TREATED (LOGGED)", acresTreatedLogged != null ? acres(acresTreatedLogged) : null],
        ["MARKED (GRID)", hasGridAssessment ? acres(zoneSummary.totals.treatedAcres) : null],
        ["FIELD TOTAL", fieldAcres > 0 ? acres(fieldAcres) : null],
        ["WIND", record.wind_speed_mph != null && record.wind_direction
          ? `${record.wind_speed_mph} mph ${record.wind_direction}` : null],
        ["TEMPERATURE", record.temperature_f != null ? `${record.temperature_f} °F` : null],
        ["APPLICATOR CERT.", has(record.applicator_cert_no)],
        ["PART 137 CERT.", has(record.part137_cert_no)],
      ];
      for (let i = 0; i < Math.max(recL.length, recR.length); i++) {
        if (recL[i]) kvRow(recL[i][0], recL[i][1], M, M + 108, y);
        if (recR[i]) kvRow(recR[i][0], recR[i][1], M + colHalf + 6, M + colHalf + 100, y);
        y += 13;
      }
      y += 2;
      pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;

      // Mission stats
      ensure(3 * 13 + 40);
      pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(110);
      pdf.text("MISSION STATS", M, y); y += 11;
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(10);
      const colW = (W - 2 * M) / 2;
      const flownLabel = isDone
        ? `${zonesFlownCount} of ${zoneRows.length}`
        : "Not determined";
      const stats: [string, string, string, string][] = [
        ["Battery start", battStart != null ? `${battStart}%` : "Not recorded",
         "Battery landed", battEnd != null ? `${battEnd}%` : "Not recorded"],
        ["Tank refills", String(tankRefills),
         "Zones flown", flownLabel],
      ];
      for (const [k1, v1, k2, v2] of stats) {
        pdf.setTextColor(110); pdf.text(k1, M, y);
        pdf.setTextColor(30); pdf.text(v1, M + colW - 12, y, { align: "right" });
        pdf.setTextColor(110); pdf.text(k2, M + colW + 12, y);
        pdf.setTextColor(30); pdf.text(v2, W - M, y, { align: "right" });
        y += 13;
      }
      if (volumeNote) {
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(MISSING_RGB[0], MISSING_RGB[1], MISSING_RGB[2]);
        pdf.setFontSize(8);
        const noteLines = pdf.splitTextToSize(volumeNote, W - 2 * M);
        pdf.text(noteLines, M, y);
        y += noteLines.length * 9 + 2;
      }
      y += 4;

      // Applicator notes — only when the applicator wrote any.
      if (pilotNotes?.trim()) {
        const wrapped = pdf.splitTextToSize(pilotNotes.trim(), W - 2 * M);
        ensure(wrapped.length * 11 + 30);
        pdf.setDrawColor(220); pdf.line(M, y, W - M, y); y += 12;
        pdf.setFont("helvetica", "bold"); pdf.setFontSize(9); pdf.setTextColor(110);
        pdf.text("APPLICATOR NOTES", M, y); y += 11;
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(9); pdf.setTextColor(30);
        pdf.text(wrapped, M, y);
        y += wrapped.length * 11 + 6;
      }

      // Signature block: part of the content FLOW, never pinned to a page
      // bottom — the old fixed placement is what overprinted the zone table.
      ensure(56);
      const sigY = y + 26;
      pdf.setDrawColor(120); pdf.setLineWidth(0.75);
      pdf.line(M, sigY, M + 220, sigY);
      pdf.line(W - M - 140, sigY, W - M, sigY);
      pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.setTextColor(110);
      pdf.text("Applicator signature", M, sigY + 10);
      pdf.text("Date", W - M - 140, sigY + 10);
      y = sigY + 20;

      // Optional appendix: the per-zone detail the main body no longer
      // enumerates. Off by default; a grower gets the summary, an agronomist
      // who wants the lattice asks for it (or takes the CSV).
      if (includeAppendix && zoneRows.length > 0) {
        newPage();
        pdf.setFont("helvetica", "bold"); pdf.setFontSize(11); pdf.setTextColor(30);
        pdf.text("APPENDIX — PER-ZONE DETAIL", M, y); y += 8;
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(8); pdf.setTextColor(110);
        pdf.text(
          `Every zone the treatment grid produced, as painted. The report body summarises these by classification and rate.`,
          M, y + 6,
        );
        y += 20;
        const AC = { rate: W - M - 170, area: W - M - 70, flown: W - M };
        pdf.setFont("helvetica", "bold"); pdf.setTextColor(140); pdf.setFontSize(7.5);
        pdf.text("ZONE", M, y);
        pdf.text("CLASSIFICATION", M + 150, y);
        pdf.text("RATE", AC.rate, y, { align: "right" });
        pdf.text("AREA", AC.area, y, { align: "right" });
        pdf.text("FLOWN", AC.flown, y, { align: "right" });
        y += 4; pdf.setDrawColor(230); pdf.line(M, y, W - M, y); y += 9;
        pdf.setFontSize(8);
        for (const z of zoneRows) {
          ensure(11);
          pdf.setFont("helvetica", "normal"); pdf.setTextColor(70);
          pdf.text(z.id.length > 26 ? `…${z.id.slice(-24)}` : z.id, M, y);
          pdf.setTextColor(30);
          pdf.text(z.issue || "Unclassified", M + 150, y);
          pdf.text(z.rateLha != null ? fmtRate(z.rateLha, unit).text : "—", AC.rate, y, { align: "right" });
          pdf.text(acres(z.acres), AC.area, y, { align: "right" });
          pdf.setTextColor(z.flown ? 34 : 150);
          pdf.text(z.flown ? "yes" : "no", AC.flown, y, { align: "right" });
          y += 10.5;
        }
      }

      // Per-page footer, drawn AFTER all content so it owns the reserved band
      // on every page: retention notice, brand, and page numbers.
      const pageCount = pdf.getNumberOfPages();
      for (let p = 1; p <= pageCount; p++) {
        pdf.setPage(p);
        pdf.setDrawColor(225); pdf.setLineWidth(0.5);
        pdf.line(M, H - FOOTER_H + 8, W - M, H - FOOTER_H + 8);
        pdf.setFont("helvetica", "normal"); pdf.setFontSize(7.5); pdf.setTextColor(130);
        pdf.text(
          "Retain this application record for the period required by federal and state regulation (typically two years or longer).",
          M, H - 28,
        );
        pdf.setFontSize(8); pdf.setTextColor(150);
        pdf.text("Generated by SwathWise · swathwise.com", M, H - 16);
        pdf.text(`Page ${p} of ${pageCount}`, W - M, H - 16, { align: "right" });
      }

      // DRAFT watermark, on every page, drawn last so nothing covers it.
      if (isDraft) {
        for (let p = 1; p <= pageCount; p++) {
          pdf.setPage(p);
          pdf.setFont("helvetica", "bold");
          pdf.setFontSize(52);
          pdf.setTextColor(248, 180, 180);
          pdf.text("DRAFT — INCOMPLETE", W / 2, H / 2, { align: "center", angle: 35 });
        }
      }
      pdf.setPage(pageCount);

      const blob = pdf.output("blob");
      const safeName = field.name.replace(/[^a-z0-9_-]+/gi, "_").slice(0, 40) || "Field";
      const filename = `${safeName}_SprayReport_${ymd}.pdf`;

      // 4) Trigger download for the user.
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url; a.download = filename; a.click();
      setTimeout(() => URL.revokeObjectURL(url), 2000);

      // 5) Upload to private storage + persist row.
      const { data: u } = await supabase.auth.getUser();
      const uid = u.user?.id;
      if (!uid) throw new Error("Not signed in.");
      const storagePath = `${uid}/${field.id}/${task.id}/${Date.now()}.pdf`;
      const up = await supabase.storage.from("field-reports")
        .upload(storagePath, blob, { contentType: "application/pdf", upsert: false });
      if (up.error) throw up.error;

      const summary = {
        pilot_name: pilotName.trim(),
        field_acres: fieldAcres,
        // Null, not zero, when no assessment computed them. `zones_source`
        // records WHICH system produced the zone figures — grid or legacy —
        // so no archived number is ever ambiguous about its origin.
        zones_source: source,
        treated_acres: isDone ? treatedAcres : null,
        total_litres: hasGridAssessment ? totalLitres : null,
        savings_pct: hasGridAssessment && zoneRows.length > 0 ? savingsPct : null,
        zones_total: isDone ? zoneRows.length : null,
        zones_flown: isDone ? zonesFlownCount : null,
        drone: activeDrone ? { name: activeDrone.name, model: activeDrone.model } : null,
        mission_date: missionDate,
        flight_log_id: effectiveFlightLogId,
        mission_record_id: effectiveMissionRecordId,
        // The application record as printed, plus the draft state — the
        // archive is the durable home of a mission's record.
        application_record: record,
        volume_applied_l: litersApplied,
        rate_l_per_ac: rateLPerAc,
        draft: isDraft,
        missing_fields: missing,
      };
      const ins = await supabase.from("field_reports").insert({
        user_id: uid,
        field_id: field.id,
        scan_id: task.id,
        flight_log_id: effectiveFlightLogId,
        pilot_name: pilotName.trim(),
        storage_path: storagePath,
        summary,
      });
      if (ins.error) throw ins.error;

      toast.success("Report generated and archived.");
      await loadReports();
    } catch (err: any) {
      console.error(err);
      toast.error(err?.message ?? "Failed to generate report");
    } finally {
      if (!restored && capRoot) {
        capRoot.style.visibility = prevVisibility;
        capRoot.style.pointerEvents = prevPointer;
        restoreMapCapture();
      }
      setGenerating(false);
    }
  };

  // ---- Auto-generate when a freshly-logged mission lands on this tab. ----
  // Fires once per flight_log_id, only for a COMPLETE record — an automatic
  // process must not quietly fill the archive with drafts.
  useEffect(() => {
    const logId = effectiveLastLog?.id;
    if (!logId || !field || generating) return;
    if (!pilotName.trim() || !missionDate) return;
    if (isDraft || missionDateError(missionDate)) return;
    if (autoGeneratedFlightReports.has(logId)) return;
    // Skip if a report for this flight log was already archived previously.
    if (reports.some(r => (r.summary as any)?.flight_log_id === logId || (r.summary as any)?.mission_record_id === logId)) {
      autoGeneratedFlightReports.add(logId);
      return;
    }
    autoGeneratedFlightReports.add(logId);
    void generate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [effectiveLastLog?.id, field?.id, missionDate, pilotName, reports]);

  const openArchived = async (r: ReportRow) => {
    const { data, error } = await supabase.storage.from("field-reports")
      .createSignedUrl(r.storage_path, 60 * 10);
    if (error || !data?.signedUrl) { toast.error("Couldn't open report"); return; }
    window.open(data.signedUrl, "_blank", "noopener");
  };

  return (
    <div className="absolute inset-0 overflow-auto bg-[#0f0f0f] text-[#f0f0f0]">
      <div className="max-w-3xl mx-auto p-8 space-y-6">
        <header className="flex items-start justify-between gap-6">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Spray Mission Report</h1>
            <p className="text-sm text-neutral-400 mt-1">
              One-page PDF and application record: this scan, its treatment-grid zones, chemical
              figures from your own rates, and the logged flight.
            </p>
          </div>
          <div className="text-right">
            {/* Same states as the report banner: no assessment shows no number,
                and a legacy result never wears the grid's styling. */}
            {!isDone ? (
              <>
                <div className="text-[10px] uppercase tracking-wider text-neutral-500">Treatment area</div>
                <div className="text-lg font-medium text-neutral-500">Not determined</div>
                <div className="text-[11px] text-neutral-600">no grid assessment</div>
              </>
            ) : source === "legacy" ? (
              <>
                <div className="text-[10px] uppercase tracking-wider text-amber-500">Legacy result</div>
                <div className="text-lg font-medium text-amber-400">{zoneRows.length} zone{zoneRows.length === 1 ? "" : "s"}</div>
                <div className="text-[11px] text-neutral-600">re-assess with the grid</div>
              </>
            ) : zoneRows.length === 0 ? (
              <>
                <div className="text-[10px] uppercase tracking-wider text-neutral-500">Assessment</div>
                <div className="text-lg font-medium text-neutral-200">Nothing marked</div>
                <div className="text-[11px] text-neutral-500">over {acres(fieldAcres)}</div>
              </>
            ) : (
              <>
                <div className="text-[10px] uppercase tracking-wider text-neutral-500">
                  {isPostFlight ? "Savings" : "Targeted"}
                </div>
                <div className="text-3xl font-semibold text-[#4CAF50] tabular-nums">
                  {isPostFlight ? `${savingsPct}%` : acres(targetedAcres)}
                </div>
                <div className="text-[11px] text-neutral-500">
                  {isPostFlight ? "vs. full-field" : `of ${acres(fieldAcres)} total`}
                </div>
              </>
            )}
          </div>
        </header>

        <div className="rounded-md border border-[#1f1f1f] bg-[#141414] p-5 space-y-4">
          <div className="grid grid-cols-2 gap-4 text-xs">
            <div>
              <div className="text-neutral-500 uppercase tracking-wider text-[10px] mb-1">Field</div>
              <div className="text-neutral-200">{field?.name ?? "-"}</div>
            </div>
            <div>
              <div className="text-neutral-500 uppercase tracking-wider text-[10px] mb-1">Total area</div>
              <div className="text-neutral-200">{fieldAcres > 0 ? acres(fieldAcres) : "Boundary not defined"}</div>
            </div>
            <div>
              <div className="text-neutral-500 uppercase tracking-wider text-[10px] mb-1">Crop</div>
              <div className="text-neutral-200">{settings.crop_type ? settings.crop_type.replace(/_/g, " ") : "-"}</div>
            </div>
            <div>
              <div className="text-neutral-500 uppercase tracking-wider text-[10px] mb-1">Drone</div>
              <div className="text-neutral-200">{activeDrone ? `${activeDrone.name} · ${activeDrone.model}` : "Not assigned"}</div>
            </div>
            <div>
              <div className="text-neutral-500 uppercase tracking-wider text-[10px] mb-1">Grid zones</div>
              <div className="text-neutral-200">
                {hasGridAssessment
                  ? `${zoneRows.length} (${zonesFlownCount} flown)`
                  : source === "legacy" ? `${zoneRows.length} (legacy result)` : "Not assessed"}
              </div>
            </div>
          </div>

          {/* ---- Mission details: required before generating. Prefilled from
                  the last logged flight so the pilot can double-check / edit. ---- */}
          <div className="pt-3 border-t border-[#1f1f1f] space-y-3">
            <div className="flex items-center justify-between">
              <div className="text-[10px] uppercase tracking-wider text-neutral-500">Mission details</div>
              {effectiveLastLog && (
                <div className="text-[10px] text-neutral-500">Prefilled from logged flight · editable</div>
              )}
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="col-span-2">
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">
                  Mission date <span className="text-red-400">*</span>
                </label>
                <input
                  type="date"
                  value={missionDate}
                  max={new Date().toISOString().slice(0, 10)}
                  onChange={e => setMissionDate(e.target.value)}
                  className={`w-full h-9 px-3 rounded bg-[#0f0f0f] border text-sm text-neutral-100 focus:outline-none ${
                    dateErr ? "border-red-500 focus:border-red-500" : "border-[#262626] focus:border-[#4CAF50]"
                  }`}
                />
                {dateErr && <div className="mt-1 text-[11px] text-red-400">{dateErr}</div>}
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Battery start (%)</label>
                <input
                  type="number" min={0} max={100} placeholder="e.g. 100"
                  value={battStartIn}
                  onChange={e => setBattStartIn(e.target.value)}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]"
                />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Battery landed (%)</label>
                <input
                  type="number" min={0} max={100} placeholder="e.g. 32"
                  value={battEndIn}
                  onChange={e => setBattEndIn(e.target.value)}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]"
                />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Tank refills</label>
                <input
                  type="number" min={0} step={1} placeholder="0"
                  value={refillsIn}
                  onChange={e => setRefillsIn(e.target.value)}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]"
                />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">
                  Volume applied ({unitLabel(unit)})
                </label>
                <input
                  type="number" min={0} step={0.1} placeholder={isImperial ? "e.g. 3.3" : "e.g. 12.5"}
                  value={litersIn}
                  onChange={e => setLitersIn(e.target.value)}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]"
                />
              </div>
              <div className="col-span-2">
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Pilot notes</label>
                <textarea
                  value={notesIn}
                  onChange={e => setNotesIn(e.target.value)}
                  rows={2}
                  placeholder="Wind picked up around 3pm, refilled tank between zones 3 and 4…"
                  className="w-full px-3 py-2 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50] resize-none"
                />
              </div>
            </div>
            {!effectiveLastLog && otherFlights.length === 0 && (
              <div className="text-[11px] text-neutral-500">
                No flight logged for this field yet, fill in the numbers manually, or log the mission from the Planner to auto-fill.
              </div>
            )}

            {/* Flights this field HAS, flown against a different scan. Offered
                with their scan named, so attaching one is a decision rather
                than a number appearing from nowhere. */}
            {!effectiveLastLog && otherFlights.length > 0 && (
              <div className="rounded border border-[#1f1f1f] bg-[#111] px-3 py-2.5 space-y-2">
                <div className="text-[11px] leading-relaxed text-neutral-400">
                  No mission is logged against <span className="text-neutral-200">this scan</span>, but
                  this field has {otherFlights.length === 1 ? "a logged flight" : "logged flights"} from
                  another scan. Attach one to use its figures, or leave it and enter this mission
                  by hand.
                </div>
                {otherFlights.map(l => (
                  <div key={l.id} className="flex items-center justify-between gap-3 rounded-sm border border-[#222] bg-[#0f0f0f] px-2.5 py-1.5">
                    <div className="min-w-0 text-[11px]">
                      <div className="text-neutral-200">
                        {new Date(`${l.date_flown}T00:00`).toLocaleDateString(undefined, {
                          year: "numeric", month: "long", day: "numeric",
                        })}
                      </div>
                      <div className="text-[10px] text-neutral-500">
                        {l.acres_treated != null ? `${l.acres_treated.toFixed(2)} ac treated` : "acreage not recorded"}
                        {" · "}
                        {l.liters_applied != null ? fmtVol(l.liters_applied, unit) : "volume not recorded"}
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => setAdoptedLog({ ...l, source: "flight_logs" })}
                      className="shrink-0 rounded-sm border border-[#4CAF50] px-2 py-1 text-[11px] text-[#4CAF50] transition-colors hover:bg-[#4CAF50]/10"
                    >
                      Attach this flight
                    </button>
                  </div>
                ))}
              </div>
            )}

            {/* An attached flight belongs to another scan; the report says so
                rather than quietly presenting it as this scan's mission. */}
            {adoptedLog && effectiveLastLog?.id === adoptedLog.id && (
              <div className="flex items-start justify-between gap-3 rounded border border-amber-900/50 bg-amber-500/5 px-3 py-2 text-[11px] leading-relaxed text-amber-300/90">
                <div>
                  Using a flight logged against a different scan of this field
                  ({new Date(`${adoptedLog.date_flown}T00:00`).toLocaleDateString()}). Its figures
                  describe that mission — check they belong on this report.
                </div>
                <button
                  type="button"
                  onClick={() => setAdoptedLog(null)}
                  className="shrink-0 text-amber-300/80 underline hover:text-amber-200"
                >
                  Detach
                </button>
              </div>
            )}
          </div>

          {/* ---- Application record. Canonical entry is the Log Flight dialog;
                  these are prefilled from it and editable here so an older
                  mission's gaps can be corrected before generating. ---- */}
          <div className="pt-3 border-t border-[#1f1f1f] space-y-3">
            <div className="text-[10px] uppercase tracking-wider text-neutral-500">Application record</div>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div className="col-span-2">
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Grower / customer</label>
                <input value={record.grower_name}
                  onChange={e => setRecord(r => ({ ...r, grower_name: e.target.value }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Product name</label>
                <input value={record.product_name}
                  onChange={e => setRecord(r => ({ ...r, product_name: e.target.value }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">EPA reg. no.</label>
                <input value={record.epa_reg_no}
                  onChange={e => setRecord(r => ({ ...r, epa_reg_no: e.target.value }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Start time</label>
                <input type="time" value={record.start_time ?? ""}
                  onChange={e => setRecord(r => ({ ...r, start_time: e.target.value || null }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">End time</label>
                <input type="time" value={record.end_time ?? ""}
                  onChange={e => setRecord(r => ({ ...r, end_time: e.target.value || null }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              {/* Observed on site. Never prefilled from a forecast API: a
                  forecast presented as an observed condition would falsify the
                  record. TODO(field-capture): automated capture at mission time. */}
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Wind speed (mph)</label>
                <input type="number" min={0} step={0.5}
                  value={record.wind_speed_mph ?? ""}
                  onChange={e => setRecord(r => ({
                    ...r, wind_speed_mph: e.target.value === "" ? null : Number(e.target.value),
                  }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Wind direction</label>
                <select value={record.wind_direction ?? ""}
                  onChange={e => setRecord(r => ({ ...r, wind_direction: e.target.value || null }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]">
                  <option value="">—</option>
                  {WIND_DIRECTIONS.map(d => <option key={d} value={d}>{d}</option>)}
                </select>
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Temperature (°F)</label>
                <input type="number" step={1}
                  value={record.temperature_f ?? ""}
                  onChange={e => setRecord(r => ({
                    ...r, temperature_f: e.target.value === "" ? null : Number(e.target.value),
                  }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Applicator cert. no.</label>
                <input value={record.applicator_cert_no}
                  onChange={e => setRecord(r => ({ ...r, applicator_cert_no: e.target.value }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
              <div>
                <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Part 137 cert. no.</label>
                <input value={record.part137_cert_no}
                  onChange={e => setRecord(r => ({ ...r, part137_cert_no: e.target.value }))}
                  className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm font-mono text-neutral-100 focus:outline-none focus:border-[#4CAF50]" />
              </div>
            </div>
          </div>

          <div>
            <label className="text-[10px] uppercase tracking-wider text-neutral-500 mb-1 block">Pilot name</label>
            <input
              value={pilotName}
              onChange={e => setPilotName(e.target.value)}
              placeholder="e.g. Sam Chen"
              className="w-full h-9 px-3 rounded bg-[#0f0f0f] border border-[#262626] text-sm text-neutral-100 focus:outline-none focus:border-[#4CAF50]"
            />
          </div>

          {reconciliations.length > 0 && (
            <div className="rounded border border-amber-900/50 bg-amber-500/5 px-3 py-2 text-[11px] leading-relaxed text-amber-300/90">
              <div className="font-semibold mb-1">
                The figures below disagree — these notes will print in the report body:
              </div>
              <ul className="list-disc space-y-1 pl-4">
                {reconciliations.map((r, i) => <li key={i}>{r.message}</li>)}
              </ul>
            </div>
          )}

          {isDraft && (
            <div className="rounded border border-red-900/50 bg-red-500/5 px-3 py-2 text-[11px] leading-relaxed text-red-300/90">
              <span className="font-semibold">This will generate as DRAFT — INCOMPLETE.</span>{" "}
              Missing: {missing.join(", ")}. Each gap prints on the report in red rather than
              being dropped; complete the record here or in the mission log to issue a final copy.
            </div>
          )}

          {zoneRows.length > 0 && (
            <div className="flex flex-wrap items-center justify-between gap-2">
              <label className="flex cursor-pointer items-center gap-2 text-[11px] text-neutral-400">
                <input
                  type="checkbox"
                  checked={includeAppendix}
                  onChange={e => setIncludeAppendix(e.target.checked)}
                  className="accent-[#4CAF50]"
                />
                Include per-zone appendix ({zoneRows.length} zones — the report body shows the
                summary either way)
              </label>
              <button
                type="button"
                onClick={() => {
                  const csv = zoneDetailCsv(zoneRows.map(z => ({
                    id: z.id, issue: z.issue, acres: z.acres, rateLha: z.rateLha, flown: z.flown,
                  })));
                  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = `${(field?.name ?? "field").replace(/[^a-z0-9_-]+/gi, "_")}_zones.csv`;
                  a.click();
                  setTimeout(() => URL.revokeObjectURL(url), 2000);
                }}
                className="text-[11px] text-neutral-400 underline hover:text-neutral-200"
              >
                Export zone detail (CSV)
              </button>
            </div>
          )}
          {hasGridAssessment && zoneSummary.allUnclassified && (
            <div className="text-[11px] text-amber-400/90">
              None of these zones is classified yet — the report will say so. Classify them from
              the Treatment Grid or the zone popups in Field View.
            </div>
          )}

          <button
            onClick={generate}
            disabled={generating || !field || !missionDate || !pilotName.trim() || !!dateErr}
            className="w-full h-10 rounded bg-[#4CAF50] hover:bg-[#43a047] text-white text-sm font-medium inline-flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            {generating
              ? (<><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>)
              : (<><Download className="h-4 w-4" /> {isDraft ? "Download Draft Report" : "Download Report"}</>)}
          </button>
          {!hasGridAssessment && (
            <div className="text-[11px] text-yellow-400/90 flex items-center gap-1.5">
              <Grid3x3 className="h-3 w-3" />{" "}
              {source === "legacy"
                ? "This scan carries only a legacy vision result. The report marks it as legacy; assess the scan in the Treatment Grid tab for a final report."
                : "No treatment-grid assessment exists for this scan; the report will state that treatment areas were not determined."}
            </div>
          )}
        </div>

        <section>
          <h2 className="text-[10px] uppercase tracking-wider text-neutral-500 mb-2">Report archive</h2>
          {reports.length === 0 ? (
            <div className="text-sm text-neutral-500 italic">No reports yet.</div>
          ) : (
            <ul className="space-y-1">
              {reports.map(r => (
                <li key={r.id}>
                  <button
                    onClick={() => openArchived(r)}
                    className="w-full flex items-center gap-3 px-3 py-2 rounded border border-[#1f1f1f] bg-[#141414] hover:bg-[#1a1a1a] text-left text-xs"
                  >
                    <FileText className="h-3.5 w-3.5 text-[#4CAF50]" />
                    <span className="text-neutral-200 flex-1">
                      {new Date(r.generated_at).toLocaleString()}
                      {r.pilot_name ? ` · ${r.pilot_name}` : ""}
                    </span>
                    {(r.summary as { draft?: boolean })?.draft && (
                      <span className="rounded-sm border border-red-900/60 px-1.5 py-0.5 text-[10px] font-semibold text-red-400">DRAFT</span>
                    )}
                    {r.summary?.savings_pct != null && (
                      <span className="text-[#4CAF50] tabular-nums">{r.summary.savings_pct}% saved</span>
                    )}
                  </button>
                </li>
              ))}
            </ul>
          )}
        </section>
      </div>
    </div>
  );
}