// Build the seed migration for a state weed catalog package.
//
//   npx tsx scripts/build-weed-catalog-seed.ts weeddatabase/Virginia_weed_catalog_v0.1
//
// Reads catalog.json, sources.json, review_queue.json and coverage.json,
// runs the same checks the package's validate_catalog.py runs (plus the ones
// the database enforces), and writes
// supabase/migrations/<stamp>_weed_catalog_seed_<state>_<version>.sql: one
// call to import_weed_catalog() with the payload inline. `supabase db push`
// applies it; the function is idempotent, so applying it again, or importing
// a later version over it, never duplicates and never touches a reviewed row.
//
// Why a migration and not a script against the API: it needs no service-role
// key on anyone's machine, it is versioned with the code that reads it, and
// the deploy path is the one every other schema change already takes.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseCatalog, summariseEntries } from "../src/lib/weedCatalog/import";

const dir = process.argv[2];
if (!dir) {
  console.error("usage: npx tsx scripts/build-weed-catalog-seed.ts <catalog package dir> [--stamp YYYYMMDDHHMMSS]");
  process.exit(2);
}
const stampArg = process.argv.indexOf("--stamp");
const stamp = stampArg > 0 ? process.argv[stampArg + 1] : new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);

const readJson = (name: string, optional = false): unknown => {
  const p = join(dir, name);
  if (!existsSync(p)) {
    if (optional) return undefined;
    console.error(`missing ${p}`);
    process.exit(2);
  }
  return JSON.parse(readFileSync(p, "utf8").replace(/^﻿/, ""));
};

const payload = parseCatalog({
  catalog: readJson("catalog.json"),
  sources: readJson("sources.json"),
  reviewQueue: readJson("review_queue.json"),
  coverage: readJson("coverage.json", true),
});

const json = JSON.stringify(payload);
const TAG = "$weedcatalog$";
if (json.includes(TAG)) {
  console.error("payload contains the dollar-quote tag; pick another tag");
  process.exit(1);
}

const summary = summariseEntries(payload.entries);
const versionSlug = payload.catalog_version.replace(/[^0-9a-z]+/gi, "_");
const out = resolve("supabase", "migrations", `${stamp}_weed_catalog_seed_${payload.state.toLowerCase()}_${versionSlug}.sql`);

const header = [
  `-- Seed: ${payload.state} weed catalog ${payload.catalog_version} (as of ${payload.as_of}).`,
  `-- Generated by scripts/build-weed-catalog-seed.ts from ${dir.replace(/\\/g, "/")}. Do not hand-edit;`,
  "-- re-run the script on a new package version to produce the next seed.",
  "--",
  `-- ${summary.total} source records: ${summary.byStatus.crop_context_sourced} named in a crop guide table,`,
  `-- ${summary.byStatus.source_index_only} in the identification index only, ${summary.byStatus.regulatory_only} in law only;`,
  `-- ${summary.unresolvedUsda} scientific names unresolved against the USDA checklist; ${payload.review_queue.length} review queue items.`,
  "-- None of these are verified farm weeds, presence claims, or aerially validated identifications.",
  "-- import_weed_catalog() is idempotent and never writes a review-owned column.",
  "",
  `SELECT public.import_weed_catalog(${TAG}${json}${TAG}::jsonb);`,
  "",
].join("\n");

writeFileSync(out, header, "utf8");
console.log(`wrote ${out}`);
console.log(`  ${payload.entries.length} entries, ${payload.sources.length} sources, ${payload.review_queue.length} queue items, ${(header.length / 1024).toFixed(0)} KB`);
